import { SiteFooter } from '../../components/site/SiteFooter'
import { SiteHeader } from '../../components/site/SiteHeader'
import { marketSections } from '../../lib/markets/data'

export const metadata = { title: 'Global Markets | NEWSiQ', description: 'Indicative global market signals across equities, currencies, commodities and crypto.', alternates: { canonical: '/markets' } }

export default function MarketsPage() {
  return <div id="top" className="min-h-screen bg-background text-foreground"><SiteHeader /><main className="mx-auto max-w-7xl px-5 py-12 lg:px-8 lg:py-16"><div className="max-w-3xl"><a href="/" className="font-mono text-[10px] uppercase tracking-[0.18em] text-primary hover:underline">← Back to live feed</a><p className="mt-8 font-mono text-[10px] uppercase tracking-[0.2em] text-primary">Global markets · indicative board</p><h1 className="mt-4 text-balance text-4xl font-semibold tracking-[-0.05em] sm:text-6xl">The world&apos;s financial pulse, in one view.</h1><p className="mt-5 max-w-2xl text-pretty text-base leading-7 text-muted-foreground">A compact watchlist for the markets that shape prices, portfolios and everyday decisions. Values below are illustrative until a live market provider is connected. Read our <a href="/about" className="text-primary hover:underline">global market intelligence approach</a> or review the <a href="/terms" className="text-primary hover:underline">financial information disclaimer</a>.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-2">{marketSections.map((section) => <section key={section.group} className="signal-panel p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-primary">{section.eyebrow}</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">{section.group}</h2></div><span className="rounded-full border border-border px-2.5 py-1 font-mono text-[9px] uppercase tracking-[0.12em] text-muted-foreground">Indicative</span></div><div className="mt-5 divide-y divide-border/70">{section.quotes.map((quote) => <div key={quote.symbol} className="flex items-center justify-between gap-4 py-4 first:pt-0 last:pb-0"><div><p className="font-mono text-xs font-bold">{quote.symbol}</p><p className="mt-1 text-xs text-muted-foreground">{quote.name}</p></div><div className="text-right"><p className="font-mono text-sm font-semibold">{quote.value}</p><p className={`mt-1 font-mono text-xs ${quote.positive ? 'text-green' : 'text-red'}`}>{quote.change}</p></div></div>)}</div><div className="mt-5 border-t border-border/70 pt-4"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Your financial impact</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{section.impact}</p></div></section>)}</div><div className="mt-8 border border-border bg-secondary/30 p-5 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Data note.</strong> This is an educational market monitor, not financial advice. Quotes are illustrative fallback values and should not be used to make trading decisions.</div></main><SiteFooter /></div>
}
