import type { Metadata } from 'next'
import { SiteFooter } from '../../components/site/SiteFooter'
import { SiteHeader } from '../../components/site/SiteHeader'
import { Breadcrumbs } from '../../components/site/Breadcrumbs'

export const metadata: Metadata = { title: 'About NEWSiQ | Global Short News Intelligence', description: 'NEWSiQ delivers concise global news in English and the local language, with market-impact context across assets and regions.', alternates: { canonical: '/about' } }

export default function AboutPage() {
  return <main className="min-h-screen bg-background text-foreground"><SiteHeader /><section className="mx-auto max-w-5xl px-5 py-16 lg:px-8 lg:py-24"><Breadcrumbs current="About" /><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-primary">About NEWSiQ</p><h1 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-0.05em] sm:text-6xl">Understand the signal before the noise takes over.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">NEWSiQ is a global short-news intelligence platform built for readers who need clarity at the speed of events.</p><div className="mt-16 grid gap-5 md:grid-cols-3"><article className="signal-panel p-6"><p className="font-mono text-xs text-primary">01 / GLOBAL</p><h2 className="mt-8 text-xl font-semibold">The world in short form</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">We surface developing stories across markets, geopolitics, technology, energy and natural events.</p></article><article className="signal-panel p-6"><p className="font-mono text-xs text-primary">02 / LOCAL</p><h2 className="mt-8 text-xl font-semibold">Two languages, one story</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Each story is presented in English alongside the language most relevant to where the event happened.</p></article><article className="signal-panel p-6"><p className="font-mono text-xs text-primary">03 / CONTEXT</p><h2 className="mt-8 text-xl font-semibold">From headline to consequence</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Analysis frames possible implications for equities, gold, silver, oil, currencies, crypto and global risk appetite.</p></article></div><section className="mt-10 border-y border-border py-10"><h2 className="text-2xl font-semibold">A clearer view of what moves markets</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">NEWSiQ helps readers organize fast-moving information, compare regional perspectives and ask better questions. Analysis is informational context, not a prediction or a recommendation to buy or sell any asset.</p></section></section><SiteFooter /></main>
}
