import type { NewsItem } from './types'

export const newsItems: NewsItem[] = [
  { id: '001', region: 'Global', category: 'Geopolitics', time: 'Context update', source: 'NEWSiQ context desk', localLabel: 'English / فارسی', breaking: true, headline: 'Strait of Hormuz remains closed as tensions rise alongside diplomatic efforts', localHeadline: 'تنگه هرمز کماکان بسته است؛ با وجود افزایش تنش‌ها و تلاش‌های دیپلماتیک', summary: 'The continued closure of the Strait of Hormuz is affecting shipping assumptions and adding pressure to the global economy, even as diplomatic channels remain active.', impact: 'Oil carries the clearest upside-risk premium; gold and silver may benefit from defensive demand; bitcoin remains sensitive to liquidity and risk appetite; equities and currencies face higher volatility; grains could see indirect freight and fertilizer-cost pressure.', confidence: 'Context only', locked: true },
  { id: '002', region: 'Japan', category: 'Markets', time: 'Illustrative trend', source: 'Tokyo market context', localLabel: 'English', headline: 'Japan equities face a cross-current from yen moves and global yields', localHeadline: 'Japan equities face a cross-current from yen moves and global yields', summary: 'Currency sensitivity and overseas rate expectations remain key variables for exporters and domestic investors.', impact: 'Potential implications for Nikkei sectors, JPY, Asia equities and global capital flows.', confidence: 'Context only' },
  { id: '003', region: 'Europe', category: 'Geopolitics', time: 'Illustrative trend', source: 'European regional context', localLabel: 'Deutsch', headline: 'Energy corridor risk keeps shipping, fuel and inflation expectations in view', localHeadline: 'Risiken für Energiekorridore rücken Schifffahrt, Treibstoff und Inflation in den Fokus', summary: 'Any disruption to key routes could change delivery assumptions and increase sensitivity across energy markets.', impact: 'Potential effects on crude oil, freight, European inflation expectations and currencies.', confidence: 'Context only', locked: true },
  { id: '004', region: 'United States', category: 'Technology', time: 'Illustrative trend', source: 'Digital asset context', localLabel: 'English', headline: 'Bitcoin trades as macro liquidity and institutional risk appetite stay in focus', localHeadline: 'Bitcoin trades as macro liquidity and institutional risk appetite stay in focus', summary: 'Digital assets remain sensitive to liquidity conditions, dollar strength and the market’s willingness to hold risk.', impact: 'Potential spillovers across bitcoin, crypto-linked equities, the dollar and high-beta assets.', confidence: 'Context only', locked: true },
  { id: '005', region: 'Southeast Asia', category: 'Disaster', time: 'Illustrative trend', source: 'Regional risk context', localLabel: 'Bahasa Indonesia', headline: 'Natural-disaster preparedness puts supply chains and insurance risk back on watchlists', localHeadline: 'Kesiapsiagaan bencana alam kembali menjadi perhatian bagi rantai pasok dan risiko asuransi', summary: 'Severe weather and seismic events can quickly affect ports, transport routes, inventories and local communities.', impact: 'Potential effects on logistics, commodities, insurers and regional manufacturing.', confidence: 'Context only' },
]
