import type { NewsItem } from './types'

export const newsItems: NewsItem[] = [
  { id: '001', region: 'Global', category: 'Markets', time: 'Illustrative trend', source: 'NEWSiQ context desk', localLabel: 'English', breaking: true, headline: 'Gold remains in focus as investors weigh growth, rates and geopolitical risk', localHeadline: 'Gold remains in focus as investors weigh growth, rates and geopolitical risk', summary: 'Bullion is drawing attention as investors balance changing interest-rate expectations with demand for defensive assets.', impact: 'Potential effects across gold, silver, the dollar, sovereign yields and broader risk appetite.', confidence: 'Context only', locked: true },
  { id: '002', region: 'Japan', category: 'Markets', time: 'Illustrative trend', source: 'Tokyo market context', localLabel: '日本語', headline: 'Japan equities face a cross-current from yen moves and global yields', localHeadline: '円相場と世界的な金利動向が日本株の重しとなる可能性', summary: 'Currency sensitivity and overseas rate expectations remain key variables for exporters and domestic investors.', impact: 'Potential implications for Nikkei sectors, JPY, Asia equities and global capital flows.', confidence: 'Context only' },
  { id: '003', region: 'Europe', category: 'Geopolitics', time: 'Illustrative trend', source: 'European regional context', localLabel: 'Deutsch', headline: 'Energy corridor risk keeps shipping, fuel and inflation expectations in view', localHeadline: 'Risiken für Energiekorridore rücken Schifffahrt, Treibstoff und Inflation in den Fokus', summary: 'Any disruption to key routes could change delivery assumptions and increase sensitivity across energy markets.', impact: 'Potential effects on crude oil, freight, European inflation expectations and currencies.', confidence: 'Context only', locked: true },
  { id: '004', region: 'United States', category: 'Technology', time: 'Illustrative trend', source: 'Digital asset context', localLabel: 'English', headline: 'Bitcoin trades as macro liquidity and institutional risk appetite stay in focus', localHeadline: 'Bitcoin trades as macro liquidity and institutional risk appetite stay in focus', summary: 'Digital assets remain sensitive to liquidity conditions, dollar strength and the market’s willingness to hold risk.', impact: 'Potential spillovers across bitcoin, crypto-linked equities, the dollar and high-beta assets.', confidence: 'Context only', locked: true },
  { id: '005', region: 'Southeast Asia', category: 'Disaster', time: 'Illustrative trend', source: 'Regional risk context', localLabel: 'Bahasa Indonesia', headline: 'Natural-disaster preparedness puts supply chains and insurance risk back on watchlists', localHeadline: 'Kesiapsiagaan bencana alam kembali menjadi perhatian bagi rantai pasok dan risiko asuransi', summary: 'Severe weather and seismic events can quickly affect ports, transport routes, inventories and local communities.', impact: 'Potential effects on logistics, commodities, insurers and regional manufacturing.', confidence: 'Context only' },
]
