'use client'

import { FormEvent, useMemo, useState } from 'react'
import JsonLd from '../components/JsonLd'
import { NewsCard } from '../components/news/NewsCard'
import { newsItems } from '../lib/news/data'
import { newsCategories, type NewsFilter } from '../lib/news/types'

export default function Home() {
  const [email, setEmail] = useState('')
  const [submitted, setSubmitted] = useState(false)
  const [filter, setFilter] = useState<NewsFilter>('Live feed')
  const [liked, setLiked] = useState<string[]>([])
  const [saved, setSaved] = useState<string[]>([])
  const visibleNews = useMemo(() => filter === 'Live feed' ? newsItems : newsItems.filter((item) => item.category === filter), [filter])
  const toggle = (setter: React.Dispatch<React.SetStateAction<string[]>>, id: string) => setter((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  const share = (headline: string, summary: string) => { if (navigator.share) navigator.share({ title: headline, text: summary }).catch(() => undefined); else navigator.clipboard?.writeText(headline) }
  function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (email.trim()) setSubmitted(true) }

  return <main className="min-h-screen bg-background text-foreground"><JsonLd /><div className="page-grid" aria-hidden="true" />
    <header className="sticky top-0 z-30 border-b border-border/80 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 lg:px-8"><a href="#top" className="flex items-center gap-3" aria-label="NEWSiQ home"><span className="brand-mark">N</span><span className="font-mono text-sm font-bold tracking-[0.28em]">NEWS<span className="text-primary">iQ</span></span></a><div className="hidden items-center gap-2 md:flex"><span className="live-dot" /><span className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Live global feed</span></div><a href="#subscribe" className="rounded-md bg-primary px-4 py-2 text-xs font-bold text-primary-foreground">Unlock analysis</a></div></header>
    <div id="top" className="relative z-10 mx-auto grid max-w-7xl lg:grid-cols-[210px_minmax(0,680px)_280px]"><aside className="hidden border-r border-border/70 px-4 py-8 lg:block"><nav className="sticky top-24 space-y-2" aria-label="News categories">{newsCategories.map((item) => <button key={item} onClick={() => setFilter(item)} className={`flex w-full items-center gap-3 rounded-md px-3 py-3 text-left text-sm ${filter === item ? 'bg-secondary font-semibold' : 'text-muted-foreground hover:bg-secondary'}`}><span className={`h-1.5 w-1.5 rounded-full ${filter === item ? 'bg-primary' : 'bg-border'}`} />{item}</button>)}</nav></aside>
      <section id="feed" className="min-w-0 border-x border-border/70"><div className="border-b border-border/70 px-5 py-7 sm:px-8"><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-primary">Short news / 24h</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">What is moving now</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Fast, verified updates from around the world. Every story is published by the NEWSiQ editorial team.</p><div className="mt-5 flex gap-2 overflow-x-auto lg:hidden">{newsCategories.map((item) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-full border px-3 py-2 text-xs ${filter === item ? 'border-primary bg-primary/10 text-primary' : 'border-border text-muted-foreground'}`}>{item}</button>)}</div></div><div className="divide-y divide-border/70">{visibleNews.map((news) => <NewsCard key={news.id} news={news} liked={liked.includes(news.id)} saved={saved.includes(news.id)} onLike={() => toggle(setLiked, news.id)} onSave={() => toggle(setSaved, news.id)} onShare={() => share(news.headline, news.summary)} />)}</div></section>
      <aside className="hidden border-l border-border/70 px-5 py-8 xl:block"><div className="sticky top-24 space-y-5"><div className="rounded-md border border-border bg-card/70 p-5"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-primary">Admin publishing</p><h2 className="mt-3 text-lg font-semibold">Only verified editors post</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Every short news update is reviewed and published by the NEWSiQ team.</p><a href="/admin" className="mt-5 block w-full rounded-md border border-border px-3 py-2 text-center text-xs font-semibold">Open admin workspace</a></div><div id="subscribe" className="rounded-md border border-primary/30 bg-primary/[0.07] p-5"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-primary">Pro intelligence</p><h2 className="mt-3 text-lg font-semibold">Go beyond the headline</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Unlock complete AI impact analysis, market links and historical context.</p><form onSubmit={handleSubmit} className="mt-5 space-y-3"><label className="sr-only" htmlFor="subscribe-email">Email address</label><input id="subscribe-email" type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Your email address" className="h-10 w-full rounded-md border border-border bg-background px-3 text-xs outline-none focus:border-primary" /><button className="h-10 w-full rounded-md bg-primary text-xs font-bold text-primary-foreground">{submitted ? 'You are on the list' : 'Join the waitlist'}</button></form></div><p className="text-[10px] leading-5 text-muted-foreground">AI analysis is informational only and is not financial advice.</p></div></aside></div>
    <footer className="relative z-10 mx-auto max-w-7xl border-t border-border px-5 py-8 text-xs text-muted-foreground lg:px-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><span className="font-mono tracking-[0.15em]">NEWSiQ.TOP</span><span>Independent intelligence for a moving world · © 2026</span></div><div className="mt-7 flex flex-wrap items-center gap-2 border-t border-border/70 pt-5"><span className="mr-3 font-mono text-[10px] uppercase tracking-[0.16em]">Payment methods</span>{['paypal','visa','mastercard','apple-pay','google-pay'].map((brand) => <span className="payment-mark" key={brand}><img src={`https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/${brand}/default.svg`} alt={brand} /></span>)}</div></footer>
  </main>
}
