'use client'

import { FormEvent, useMemo, useState } from 'react'
import JsonLd from '../components/JsonLd'

type NewsItem = { id: string; region: string; category: string; time: string; source: string; localLabel: string; headline: string; localHeadline: string; summary: string; impact: string; confidence: string; locked?: boolean; breaking?: boolean }

const newsItems: NewsItem[] = [
  { id: '001', region: 'Indonesia', category: 'Disaster', time: '2 min ago', source: 'Local emergency agencies', localLabel: 'Bahasa Indonesia', breaking: true, headline: 'Strong earthquake strikes eastern Indonesia; tsunami monitoring begins', localHeadline: 'Gempa kuat melanda Indonesia bagian timur; pemantauan tsunami dimulai', summary: 'A powerful offshore earthquake has triggered emergency assessments across nearby islands. Officials are checking coastal infrastructure and transport routes.', impact: 'Potential disruption to regional logistics, nickel supply routes and insurance risk', confidence: '91.6%' },
  { id: '002', region: 'Japan', category: 'Markets', time: '8 min ago', source: 'Tokyo exchange feeds', localLabel: '日本語', headline: 'Japan stocks open lower as exporters absorb a stronger yen', localHeadline: '円高を受け、輸出関連株が下落して日本株は安く始まる', summary: 'The Nikkei opened under pressure as currency moves reshape expectations for exporters and domestic demand.', impact: 'Full analysis covers FX, Asia equities and global risk appetite', confidence: '88.4%', locked: true },
  { id: '003', region: 'Europe', category: 'Geopolitics', time: '16 min ago', source: 'Verified regional desks', localLabel: 'Deutsch', headline: 'European officials call for an emergency review of energy corridors', localHeadline: 'Europäische Vertreter fordern eine Notfallprüfung der Energiekorridore', summary: 'A coordinated review could affect near-term energy procurement and shipping assumptions across several member states.', impact: 'Unlock commodity, shipping and currency implications', confidence: '84.9%', locked: true },
]

const navItems = ['Live feed', 'Markets', 'Geopolitics', 'Technology']
function LockIcon() { return <svg aria-hidden="true" className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg> }
function GlobeIcon() { return <svg aria-hidden="true" className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.4 2.5 3.5 5.5 3.5 9S14.4 18.5 12 21c-2.4-2.5-3.5-5.5-3.5-9S9.6 5.5 12 3Z"/></svg> }

export default function Home() {
  const [email, setEmail] = useState(''); const [submitted, setSubmitted] = useState(false); const [filter, setFilter] = useState('Live feed'); const [liked, setLiked] = useState<string[]>([]); const [saved, setSaved] = useState<string[]>([])
  const visibleNews = useMemo(() => filter === 'Live feed' ? newsItems : newsItems.filter((item) => item.category === filter), [filter])
  function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (email.trim()) setSubmitted(true) }
  function toggle(setter: React.Dispatch<React.SetStateAction<string[]>>, id: string) { setter((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]) }
  function share(item: NewsItem) { if (navigator.share) navigator.share({ title: item.headline, text: item.summary }).catch(() => undefined); else navigator.clipboard?.writeText(item.headline) }

  return <main className="min-h-screen bg-background text-foreground"><JsonLd/><div className="page-grid" aria-hidden="true"/>
    <header className="sticky top-0 z-30 border-b border-border/80 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 lg:px-8"><a href="#top" className="flex items-center gap-3" aria-label="NEWSiQ home"><span className="brand-mark">N</span><span className="font-mono text-sm font-bold tracking-[0.28em]">NEWS<span className="text-primary">iQ</span></span></a><div className="hidden items-center gap-2 md:flex"><span className="live-dot"/><span className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Live global feed</span></div><div className="flex items-center gap-3"><span className="hidden text-xs text-muted-foreground sm:inline">English / Local</span><a href="#subscribe" className="rounded-md bg-primary px-4 py-2 text-xs font-bold text-primary-foreground transition-transform hover:-translate-y-0.5">Unlock analysis</a></div></div></header>
    <div id="top" className="relative z-10 mx-auto grid max-w-7xl lg:grid-cols-[210px_minmax(0,680px)_280px]"><aside className="hidden border-r border-border/70 px-4 py-8 lg:block"><nav className="sticky top-24 space-y-2" aria-label="News categories">{navItems.map((item) => <button key={item} onClick={() => setFilter(item)} className={`flex w-full items-center gap-3 rounded-md px-3 py-3 text-left text-sm ${filter === item ? 'bg-secondary font-semibold text-foreground' : 'text-muted-foreground hover:bg-secondary hover:text-foreground'}`}><span className={`h-1.5 w-1.5 rounded-full ${filter === item ? 'bg-primary' : 'bg-border'}`}/>{item}</button>)}</nav></aside>
      <section id="feed" className="min-w-0 border-x border-border/70"><div className="border-b border-border/70 px-5 py-7 sm:px-8"><div className="flex items-center justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-primary">Short news / 24h</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">What is moving now</h1></div><span className="rounded-full border border-primary/30 bg-primary/10 px-3 py-1.5 font-mono text-[10px] text-primary">142 regions</span></div><p className="mt-3 max-w-lg text-sm leading-6 text-muted-foreground">Fast, verified updates from around the world. Every story is published by the NEWSiQ editorial team.</p><div className="mt-5 flex gap-2 overflow-x-auto lg:hidden">{navItems.map((item) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-full border px-3 py-2 text-xs ${filter === item ? 'border-primary bg-primary/10 text-primary' : 'border-border text-muted-foreground'}`}>{item}</button>)}</div></div>
        <div className="divide-y divide-border/70">{visibleNews.map((news) => <article key={news.id} className="px-5 py-7 transition-colors hover:bg-card/40 sm:px-8"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.14em] text-muted-foreground"><span className="text-primary">{news.region}</span><span>·</span><span>{news.category}</span><span>·</span><span>{news.time}</span>{news.breaking && <span className="ml-auto rounded bg-red-400/10 px-2 py-1 text-red-300">Breaking</span>}</div><h2 className="mt-4 text-xl font-semibold leading-snug tracking-[-0.02em]">{news.headline}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{news.summary}</p><div className="mt-5 rounded-md border border-border bg-secondary/60 p-4"><div className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.12em] text-primary"><GlobeIcon/> {news.localLabel}</span><span className="text-[10px] text-muted-foreground">Local version</span></div><p className="mt-3 text-sm font-medium leading-6 text-foreground/90">{news.localHeadline}</p></div><div className={`mt-5 rounded-md border p-4 ${news.locked ? 'border-primary/30 bg-primary/[0.06]' : 'border-border bg-card/50'}`}><div className="flex items-center justify-between gap-4"><span className="font-mono text-[10px] uppercase tracking-[0.15em] text-primary">AI market impact</span><span className="font-mono text-[10px] text-muted-foreground">Confidence {news.confidence}</span></div><p className={`mt-3 text-sm leading-6 ${news.locked ? 'text-muted-foreground blur-[3px] select-none' : 'text-foreground/85'}`}>{news.impact}</p>{news.locked && <a href="#subscribe" className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-primary hover:underline"><LockIcon/> Subscribe to unlock full analysis</a>}</div><div className="mt-4 flex items-center justify-between border-t border-border/70 pt-4 text-[11px] text-muted-foreground"><span>Source: {news.source}</span><div className="flex items-center gap-4"><button aria-label={`Like ${news.headline}`} onClick={() => toggle(setLiked, news.id)} className={liked.includes(news.id) ? 'text-primary' : 'hover:text-primary'}>Like</button><button aria-label={`Save ${news.headline}`} onClick={() => toggle(setSaved, news.id)} className={saved.includes(news.id) ? 'text-primary' : 'hover:text-primary'}>Save</button><button aria-label={`Share ${news.headline}`} onClick={() => share(news)} className="hover:text-primary">Share</button></div></div></article>)}</div></section>
      <aside className="hidden border-l border-border/70 px-5 py-8 xl:block"><div className="sticky top-24 space-y-5"><div className="rounded-md border border-border bg-card/70 p-5"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-primary">Admin publishing</p><h2 className="mt-3 text-lg font-semibold">Only verified editors post</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">No open posting. Every short news update is reviewed and published by the NEWSiQ team.</p><a href="/admin" className="mt-5 block w-full rounded-md border border-border px-3 py-2 text-center text-xs font-semibold text-muted-foreground transition-colors hover:border-primary hover:text-primary">Open admin workspace</a></div><div id="subscribe" className="rounded-md border border-primary/30 bg-primary/[0.07] p-5"><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-primary">Pro intelligence</p><h2 className="mt-3 text-lg font-semibold">Go beyond the headline</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Unlock complete AI impact analysis, market links and historical context.</p><form onSubmit={handleSubmit} className="mt-5 space-y-3"><label className="sr-only" htmlFor="subscribe-email">Email address</label><input id="subscribe-email" type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Your email address" className="h-10 w-full rounded-md border border-border bg-background px-3 text-xs outline-none focus:border-primary"/><button className="h-10 w-full rounded-md bg-primary text-xs font-bold text-primary-foreground">{submitted ? 'You are on the list' : 'Join the waitlist'}</button></form></div><p className="text-[10px] leading-5 text-muted-foreground">AI analysis is informational only and is not financial advice.</p></div></aside></div>
    <footer className="relative z-10 mx-auto max-w-7xl border-t border-border px-5 py-8 text-xs text-muted-foreground lg:px-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><span className="font-mono tracking-[0.15em]">NEWSiQ.TOP</span><span>Independent intelligence for a moving world · © 2026</span></div><div className="mt-7 flex flex-col gap-3 border-t border-border/70 pt-5 sm:flex-row sm:items-center sm:justify-between"><span className="font-mono text-[10px] uppercase tracking-[0.16em]">Payment methods</span><div className="flex flex-wrap items-center gap-2" aria-label="Accepted payment methods"><span className="payment-mark"><img src="https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/paypal/default.svg" alt="PayPal"/></span><span className="payment-mark"><img src="https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/visa/default.svg" alt="Visa"/></span><span className="payment-mark"><img src="https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/mastercard/default.svg" alt="Mastercard"/></span><span className="payment-mark"><img src="https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/apple-pay/default.svg" alt="Apple Pay"/></span><span className="payment-mark"><img src="https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/google-pay/default.svg" alt="Google Pay"/></span></div></div></footer>
  </main>
}
